name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Elixir ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  build:
    name: Build and push Docker image
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      run: |
        echo "Build"
        echo "${{github.ref}}"
  release:
    name: Release
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - test
    runs-on: ubuntu-latest
    environment: build
    steps:
      - run: echo "Release"