on:
  push:
    tags:
      - 'v*'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  release:
    name: Release
    needs:
      - test
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Keila ${{ github.ref }}
          draft: false
          prerelease: false